# Generated by Django 3.1 on 2023-03-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
