# Generated by Django 3.1 on 2023-03-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_quality_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality_grade',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
