# Generated by Django 3.1 on 2023-03-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230328_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality_grade',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
