# Generated by Django 3.1 on 2023-03-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230328_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quality_grade',
        ),
    ]
